### ISSUE TITLE
Checklist of things to add

### ISSUE THREAD

**Issue by jemus42** [jemus42/theincompaRable#2]
There are so many possibilities, so I thought I should probably keep track of ideas.
- [x] Projection of yearly growth (exponential? fit of epcount/year)
  - [See discarded plots](http://stats.jemu.name/theincomparable/discarded_plots.html#yearly-growth)
- [x] More person statistics. 
- [x] Something with 'categories' field. 
  - Limitation: Only really useful for the main show
  - Maybe duration by category? Easy, but probably not very interesting
  - Counts by category are easy, too
## Per-show analysis
- [x] Game Show: Categorize by game played
  - Implementation: Can be regex'd out of 'title' field or through the appropriate feeds from the website
- [x] Main Show: Subsegment analysis (Old Movie Club, Rocket Surgery, …)
- [ ] Network analysis of panelists
